name: floating_action_row
description: A Flutter package that provides a widget with a row or column of floating action buttons.
version: 0.1.0
homepage: https://github.com/niklas-8/floating_action_row

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter: